
import { JuzData } from './types';

export const JUZ_LIST: JuzData[] = [
  { id: 1, name: "Alif Lam Mim", arabicName: "آلم", startSurah: "Al-Fatihah 1", endSurah: "Al-Baqarah 141", link: "http://j.mp/2b8SiNO", description: "Beginning of the Revelation, the opening and the first part of Al-Baqarah." },
  { id: 2, name: "Sayaqul", arabicName: "سيقول", startSurah: "Al-Baqarah 142", endSurah: "Al-Baqarah 252", link: "http://j.mp/2b8RJmQ", description: "Focuses on the changing of the Qibla and laws for the new community." },
  { id: 3, name: "Tilkal Rusul", arabicName: "تلك الرسل", startSurah: "Al-Baqarah 253", endSurah: "Al-Imran 92", link: "http://j.mp/2bFSrtF", description: "Contains the Verse of the Throne (Ayat al-Kursi) and the end of Al-Baqarah." },
  { id: 4, name: "Lan Tanalu", arabicName: "لن تنالوا", startSurah: "Al-Imran 93", endSurah: "An-Nisa 23", link: "http://j.mp/2b8SXi3", description: "Details on charity, the Battle of Uhud, and family laws." },
  { id: 5, name: "Wal Muhsanat", arabicName: "والمحصنات", startSurah: "An-Nisa 24", endSurah: "An-Nisa 147", link: "http://j.mp/2b8RZm3", description: "Social justice, rights of women, and orphans." },
  { id: 6, name: "La Yuhibbullah", arabicName: "لا يحب الله", startSurah: "An-Nisa 148", endSurah: "Al-Ma'idah 81", link: "http://j.mp/28MBohs", description: "Discussion on the People of the Book and legal rulings." },
  { id: 7, name: "Wa Iza Sami'u", arabicName: "وإذا سمعوا", startSurah: "Al-Ma'idah 82", endSurah: "Al-An'am 110", link: "http://j.mp/2bFRIZC", description: "Dietary laws, covenants, and the start of Al-An'am." },
  { id: 8, name: "Wa Lau Annana", arabicName: "ولو أننا", startSurah: "Al-An'am 111", endSurah: "Al-A'raf 87", link: "http://j.mp/2bufF7o", description: "The nature of faith and the stories of previous prophets." },
  { id: 9, name: "Qalal Mala'u", arabicName: "قال الملأ", startSurah: "Al-A'raf 88", endSurah: "Al-Anfal 40", link: "http://j.mp/2byr1bu", description: "The struggle between truth and falsehood." },
  { id: 10, name: "Wa'lamu", arabicName: "واعلموا", startSurah: "Al-Anfal 41", endSurah: "At-Taubah 92", link: "http://j.mp/2bHfyUH", description: "Laws of war, peace, and the nature of hypocrites." },
  { id: 11, name: "Ya'tazirun", arabicName: "يعتذرون", startSurah: "At-Taubah 93", endSurah: "Hud 5", link: "http://j.mp/2bHf80y", description: "Repentance and the stories of Yunus and Hud." },
  { id: 12, name: "Wa Ma Min Daabbah", arabicName: "وما من دابة", startSurah: "Hud 6", endSurah: "Yusuf 52", link: "http://j.mp/2bWnTby", description: "Prophetic history and the beginning of Prophet Yusuf's story." },
  { id: 13, name: "Wa Ma Ubabri'u", arabicName: "وما أبرئ", startSurah: "Yusuf 53", endSurah: "Ibrahim 52", link: "http://j.mp/2bFTiKQ", description: "Conclusion of Yusuf's story and themes of gratitude." },
  { id: 14, name: "Rubama", arabicName: "ربما", startSurah: "Al-Hijr 1", endSurah: "An-Nahl 128", link: "http://j.mp/2b8SUTA", description: "God's signs in nature and warnings to the arrogant." },
  { id: 15, name: "Subhanallazi", arabicName: "سبحان الذي", startSurah: "Al-Isra 1", endSurah: "Al-Kahf 74", link: "http://j.mp/2bFRQIM", description: "The Night Journey and the People of the Cave." },
  { id: 16, name: "Qala Alam", arabicName: "قال ألم", startSurah: "Al-Kahf 75", endSurah: "Ta-Ha 135", link: "http://j.mp/2b8SegG", description: "Musa and Khidr, Dhul-Qarnayn, and the story of Maryam." },
  { id: 17, name: "Iqtaraba Linnas", arabicName: "اقترب للناس", startSurah: "Al-Anbiya 1", endSurah: "Al-Hajj 78", link: "http://j.mp/2brHsFz", description: "Stories of the Prophets and the significance of the Pilgrimage." },
  { id: 18, name: "Qad Aflaha", arabicName: "قد أفلح", startSurah: "Al-Mu'minun 1", endSurah: "Al-Furqan 20", link: "http://j.mp/2b8SCfc", description: "Characteristics of believers and light (An-Nur)." },
  { id: 19, name: "Wa Qalallazina", arabicName: "وقال الذين", startSurah: "Al-Furqan 21", endSurah: "An-Naml 55", link: "http://j.mp/2bFSq95", description: "Distinction between right and wrong, and the story of the Poets." },
  { id: 20, name: "Amman Khalaqa", arabicName: "أمن خلق", startSurah: "An-Naml 56", endSurah: "Al-Ankabut 45", link: "http://j.mp/2brI1zc", description: "Creation of the heavens and earth and the spider's web parable." },
  { id: 21, name: "Utlu Ma Uhiya", arabicName: "اتل ما أوحي", startSurah: "Al-Ankabut 46", endSurah: "Al-Ahzab 30", link: "http://j.mp/2b8VcBO", description: "Recitation of revelation and social conduct." },
  { id: 22, name: "Wa Man Yaqnut", arabicName: "ومن يقنت", startSurah: "Al-Ahzab 31", endSurah: "Ya-Sin 27", link: "http://j.mp/2bFRxNP", description: "Devotion to Allah and the heart of the Quran (Ya-Sin)." },
  { id: 23, name: "Wa Maliya", arabicName: "وما لي", startSurah: "Ya-Sin 28", endSurah: "Az-Zumar 31", link: "http://j.mp/2brItxm", description: "Resurrection, the ranks (As-Saffat), and divine unity." },
  { id: 24, name: "Faman Azlamu", arabicName: "فمن أظلم", startSurah: "Az-Zumar 32", endSurah: "Fussilat 46", link: "http://j.mp/2brHKw5", description: "Forgiveness and the clarity of the Quran." },
  { id: 25, name: "Ilaihi Yuraddu", arabicName: "إليه يرد", startSurah: "Fussilat 47", endSurah: "Al-Jathiyah 37", link: "http://j.mp/2brImlf", description: "Consultation, gold ornaments, and smoking/smoke sign." },
  { id: 26, name: "Ha Mim", arabicName: "حم", startSurah: "Al-Ahqaf 1", endSurah: "Adh-Dhariyat 30", link: "http://j.mp/2bFRHF2", description: "The victory (Al-Fath) and the private apartments (Al-Hujurat)." },
  { id: 27, name: "Qala Fama Khatbukum", arabicName: "قال فما خطبكم", startSurah: "Adh-Dhariyat 31", endSurah: "Al-Hadid 29", link: "http://j.mp/2bFRXno", description: "The Most Merciful (Ar-Rahman) and the Inevitable Event." },
  { id: 28, name: "Qad Sami' Allah", arabicName: "قد سمع الله", startSurah: "Al-Mujadila 1", endSurah: "At-Tahrim 12", link: "http://j.mp/2brI3ai", description: "Social laws for the household and community." },
  { id: 29, name: "Tabarakallazi", arabicName: "تبارك الذي", startSurah: "Al-Mulk 1", endSurah: "Al-Mursalat 50", link: "http://j.mp/2bFRyBF", description: "Sovereignty of Allah and the shorter Meccan Surahs." },
  { id: 30, name: "Amma Yatasa'alun", arabicName: "عم يتساءلون", startSurah: "An-Naba 1", endSurah: "An-Nas 6", link: "http://j.mp/2bFREcc", description: "The Great News and the final short surahs for prayer." },
];
